name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      json-file-path:
        description: 'Path to the JSON file'
        required: true

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq

      - name: Read and print JSON values
        run: |
          json_file_path=${{ github.event.inputs.json-file-path }}
          echo "Processing JSON file at $json_file_path"

          # Parse and print specific values from the JSON file
          pkp_id=$(jq -r '.pkp-id' $json_file_path)
          title=$(jq -r '.title' $json_file_path)
          description=$(jq -r '.description' $json_file_path)
          id_list=$(jq -r '.scope.documents.id-list-filter | join(", ")' $json_file_path)

          echo "pkp-id: $pkp_id"
          echo "title: $title"
          echo "description: $description"
          echo "id-list: $id_list"
          
          # Add your specific logic to process JSON values as needed
