name: Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      json-file-path:
        description: 'Path to the JSON file'
        required: true

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Process JSON
        run: |
          echo "Processing JSON file at ${{ github.event.inputs.json-file-path }}"
          # Add your logic here to process the JSON file
